// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj5FmKTro87d6gvkylKwBI2Non_suNQH8',
    appId: '1:554859336568:web:5471dadec7133882312e8d',
    messagingSenderId: '554859336568',
    projectId: 'mad-fyp-adb09',
    authDomain: 'mad-fyp-adb09.firebaseapp.com',
    storageBucket: 'mad-fyp-adb09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuiCTcNEjfzo6ubZMAUd6jcZz3DSk9kGs',
    appId: '1:554859336568:android:18b005a39b686bbd312e8d',
    messagingSenderId: '554859336568',
    projectId: 'mad-fyp-adb09',
    storageBucket: 'mad-fyp-adb09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq75ebDKB3cA2tC4YXxkYTcZPyoi53f8U',
    appId: '1:554859336568:ios:bb669c1e890c62b4312e8d',
    messagingSenderId: '554859336568',
    projectId: 'mad-fyp-adb09',
    storageBucket: 'mad-fyp-adb09.firebasestorage.app',
    iosBundleId: 'com.example.abrarFypMad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq75ebDKB3cA2tC4YXxkYTcZPyoi53f8U',
    appId: '1:554859336568:ios:bb669c1e890c62b4312e8d',
    messagingSenderId: '554859336568',
    projectId: 'mad-fyp-adb09',
    storageBucket: 'mad-fyp-adb09.firebasestorage.app',
    iosBundleId: 'com.example.abrarFypMad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj5FmKTro87d6gvkylKwBI2Non_suNQH8',
    appId: '1:554859336568:web:5471dadec7133882312e8d',
    messagingSenderId: '554859336568',
    projectId: 'mad-fyp-adb09',
    authDomain: 'mad-fyp-adb09.firebaseapp.com',
    storageBucket: 'mad-fyp-adb09.firebasestorage.app',
  );

}